# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build

on:
  push:
    branches: [ devel ]
  pull_request:
    branches: [ devel ]

jobs:

  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m venv testenv
        . testenv/bin/activate
        python -m pip install --upgrade pip setuptools
        python -m pip install git+https://github.com/radical-cybertools/radical.utils.git@devel
        python -m pip install --upgrade .
        python -m pip install coverage pytest pytest-timeout
    - name: Test with pytest
      env:
        LOC: testenv/lib/python3.7/site-packages
      run: |
        . testenv/bin/activate
        coverage run --include=$LOC/radical/saga/* -m pytest -ra --timeout=600 -vvv --showlocals tests/adaptors/ tests/unittests/
        coverage xml
    - name: Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
