name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        platform: ["ubuntu-latest"]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install curl dnsutils jq netcat shellcheck jq testssl.sh python3
    - name: Run tests
      run: ./util/test
