name: Build and deploy pytgcalls documentation to GitHub Pages
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/build_and_deploy_pytgcalls_documentation.yaml'
      - 'pytgcalls/**'
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.6'
          architecture: 'x64'
      - name: Install and Build
        run: |
          python -m pip install --upgrade pip
          pip install tgcalls pdoc3 pyrogram telethon
          pdoc pytgcalls/pytgcalls --html --force --template-dir pytgcalls/pdoc
          mv html/pytgcalls/* html
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: html
