name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3

      # Re-use node_modules between runs until package-lock.json changes.
      - name: Cache node_modules
        id: internal-cache-node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: internal-node_modules-ubuntu-latest.x-${{ hashFiles('package-lock.json') }}

      # Re-use ~/.elm between runs until elm.json or review/elm.json changes.
      # The Elm compiler saves downloaded Elm packages to ~/.elm.
      - name: Cache ~/.elm
        uses: actions/cache@v2
        with:
          path: ~/.elm
          key: elm-${{ hashFiles('elm.json', 'review/elm.json') }}

      - name: Install npm dependencies
        if: steps.cache-node_modules.outputs.cache-hit != 'true'
        run: npm ci
      - run: npm test
