name: Java:



on: [ main ]



jobs:
 maven/test:
  runs-on: cimg/openjdk:11.0
  runs-on: cimg/postgres:14.1
  
  env:
   POSTGRES_USER : postgres
   POSTGRES_PASSWORD : password
   POSTGRES_DB : cfd
   DOCKERIZE_VERSION : v0.6.1
  
  steps:
   - name: Install dockerize
     run: wget   https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz 
   - name: Wait for db
     run: dockerize   -wait tcp://localhost:5432 -timeout 1m 
  
  
  
 
  


