name: Node:



on: [ main ]



jobs:
 test:
  runs-on: cimg/node:16.16
  
  
  steps:
   - name: 
    run: checkout 
   - name: 
    run: node/install-packages  pkg-manager: yarn 
   - name: Run tests
    run: yarn  run test:unit 
  
  
  
  
 cypress/run::
  runs-on: node-cypress
  
  
  steps:
   - name: 
    run: yarn  run test:e2e --headless 
  
  
  
  


