name: Vue:



on: [ main ]



jobs:
	path-filtering/filter:
		
		
		steps:
			- name: 
			 run:  base-revision  main 
			- name: 
			 run: mapping  |  frontend/.* run-frontend true  backend/.* run-backend true 
			- name: 
			 run: config-path  ".circleci/dynamic_config.yml" 
		
		
		
		


