name: Vue

env:
 run-frontend : false
 run-backend : false


on: [ main ]



jobs:
 frontend-test:
  runs-on: cimg/node:15.1
  
  if:  pipeline.parameters.run-frontend
  
  
  steps:
   - name: 
    run: checkout 
   - name: 
    run: node/install-packages 
   - name: Run tests
    run: npm  test 
  
  
  
  
 backend-test:
  runs-on:  cimg/python:3.8
  
  if: pipeline.parameters.run-backend
  
  
  steps:
   - name: 
    run: checkout 
   - name: 
    run: python/install-package  pkg-manager: pip 
   - name: Run tests
    run: pytest 
  
  
  
