/**
 * generated by Xtext 2.27.0
 */
package org.xtext.example.mydsl10.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Command2 Run Tool</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl10.myDsl.Command2RunTool#getToolkey <em>Toolkey</em>}</li>
 *   <li>{@link org.xtext.example.mydsl10.myDsl.Command2RunTool#getParameters <em>Parameters</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl10.myDsl.MyDslPackage#getCommand2RunTool()
 * @model
 * @generated
 */
public interface Command2RunTool extends EObject
{
  /**
   * Returns the value of the '<em><b>Toolkey</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Toolkey</em>' attribute list.
   * @see org.xtext.example.mydsl10.myDsl.MyDslPackage#getCommand2RunTool_Toolkey()
   * @model unique="false"
   * @generated
   */
  EList<String> getToolkey();

  /**
   * Returns the value of the '<em><b>Parameters</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parameters</em>' attribute list.
   * @see org.xtext.example.mydsl10.myDsl.MyDslPackage#getCommand2RunTool_Parameters()
   * @model unique="false"
   * @generated
   */
  EList<String> getParameters();

} // Command2RunTool
