/**
 * generated by Xtext 2.27.0
 */
package org.xtext.example.mydsl10.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Command2 Run One</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl10.myDsl.Command2RunOne#getCommand_conditional <em>Command conditional</em>}</li>
 *   <li>{@link org.xtext.example.mydsl10.myDsl.Command2RunOne#getTool <em>Tool</em>}</li>
 *   <li>{@link org.xtext.example.mydsl10.myDsl.Command2RunOne#getParameters <em>Parameters</em>}</li>
 *   <li>{@link org.xtext.example.mydsl10.myDsl.Command2RunOne#getCommand_string <em>Command string</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl10.myDsl.MyDslPackage#getCommand2RunOne()
 * @model
 * @generated
 */
public interface Command2RunOne extends EObject
{
  /**
   * Returns the value of the '<em><b>Command conditional</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl10.myDsl.IFThenElseRun}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Command conditional</em>' containment reference list.
   * @see org.xtext.example.mydsl10.myDsl.MyDslPackage#getCommand2RunOne_Command_conditional()
   * @model containment="true"
   * @generated
   */
  EList<IFThenElseRun> getCommand_conditional();

  /**
   * Returns the value of the '<em><b>Tool</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl10.myDsl.Tool_framework}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tool</em>' containment reference list.
   * @see org.xtext.example.mydsl10.myDsl.MyDslPackage#getCommand2RunOne_Tool()
   * @model containment="true"
   * @generated
   */
  EList<Tool_framework> getTool();

  /**
   * Returns the value of the '<em><b>Parameters</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parameters</em>' attribute list.
   * @see org.xtext.example.mydsl10.myDsl.MyDslPackage#getCommand2RunOne_Parameters()
   * @model unique="false"
   * @generated
   */
  EList<String> getParameters();

  /**
   * Returns the value of the '<em><b>Command string</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Command string</em>' attribute list.
   * @see org.xtext.example.mydsl10.myDsl.MyDslPackage#getCommand2RunOne_Command_string()
   * @model unique="false"
   * @generated
   */
  EList<String> getCommand_string();

} // Command2RunOne
