/**
 * generated by Xtext 2.27.0
 */
package org.xtext.example.mydsl10.myDsl;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl10.myDsl.MyDslPackage
 * @generated
 */
public interface MyDslFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyDslFactory eINSTANCE = org.xtext.example.mydsl10.myDsl.impl.MyDslFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Pipeline</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Pipeline</em>'.
   * @generated
   */
  Pipeline createPipeline();

  /**
   * Returns a new object of class '<em>When</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>When</em>'.
   * @generated
   */
  When createWhen();

  /**
   * Returns a new object of class '<em>Job If Then Else</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Job If Then Else</em>'.
   * @generated
   */
  JobIfThenElse createJobIfThenElse();

  /**
   * Returns a new object of class '<em>Job</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Job</em>'.
   * @generated
   */
  Job createJob();

  /**
   * Returns a new object of class '<em>Strategy</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Strategy</em>'.
   * @generated
   */
  Strategy createStrategy();

  /**
   * Returns a new object of class '<em>Steps</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Steps</em>'.
   * @generated
   */
  Steps createSteps();

  /**
   * Returns a new object of class '<em>Step Options</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Step Options</em>'.
   * @generated
   */
  StepOptions createStepOptions();

  /**
   * Returns a new object of class '<em>Steps1</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Steps1</em>'.
   * @generated
   */
  Steps1 createSteps1();

  /**
   * Returns a new object of class '<em>Steps2</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Steps2</em>'.
   * @generated
   */
  Steps2 createSteps2();

  /**
   * Returns a new object of class '<em>Steps3</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Steps3</em>'.
   * @generated
   */
  Steps3 createSteps3();

  /**
   * Returns a new object of class '<em>Tool framework</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Tool framework</em>'.
   * @generated
   */
  Tool_framework createTool_framework();

  /**
   * Returns a new object of class '<em>Environment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Environment</em>'.
   * @generated
   */
  Environment createEnvironment();

  /**
   * Returns a new object of class '<em>Artifact</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Artifact</em>'.
   * @generated
   */
  Artifact createArtifact();

  /**
   * Returns a new object of class '<em>Command</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Command</em>'.
   * @generated
   */
  Command createCommand();

  /**
   * Returns a new object of class '<em>Command1</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Command1</em>'.
   * @generated
   */
  Command1 createCommand1();

  /**
   * Returns a new object of class '<em>Command2</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Command2</em>'.
   * @generated
   */
  Command2 createCommand2();

  /**
   * Returns a new object of class '<em>Command2 Env</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Command2 Env</em>'.
   * @generated
   */
  Command2Env createCommand2Env();

  /**
   * Returns a new object of class '<em>Command2 Run Multiple</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Command2 Run Multiple</em>'.
   * @generated
   */
  Command2RunMultiple createCommand2RunMultiple();

  /**
   * Returns a new object of class '<em>Command2 Run One</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Command2 Run One</em>'.
   * @generated
   */
  Command2RunOne createCommand2RunOne();

  /**
   * Returns a new object of class '<em>Command2 Uses</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Command2 Uses</em>'.
   * @generated
   */
  Command2Uses createCommand2Uses();

  /**
   * Returns a new object of class '<em>Command2 Run Tool</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Command2 Run Tool</em>'.
   * @generated
   */
  Command2RunTool createCommand2RunTool();

  /**
   * Returns a new object of class '<em>If Then Else</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>If Then Else</em>'.
   * @generated
   */
  IfThenElse createIfThenElse();

  /**
   * Returns a new object of class '<em>If Then Else alt1</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>If Then Else alt1</em>'.
   * @generated
   */
  IfThenElse_alt1 createIfThenElse_alt1();

  /**
   * Returns a new object of class '<em>IF Then Else Run</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>IF Then Else Run</em>'.
   * @generated
   */
  IFThenElseRun createIFThenElseRun();

  /**
   * Returns a new object of class '<em>IF Then Else Steps</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>IF Then Else Steps</em>'.
   * @generated
   */
  IFThenElseSteps createIFThenElseSteps();

  /**
   * Returns a new object of class '<em>IF Then Else Steps alt1</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>IF Then Else Steps alt1</em>'.
   * @generated
   */
  IFThenElseSteps_alt1 createIFThenElseSteps_alt1();

  /**
   * Returns a new object of class '<em>IF Then Else Jobs Steps alt2</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>IF Then Else Jobs Steps alt2</em>'.
   * @generated
   */
  IFThenElseJobsSteps_alt2 createIFThenElseJobsSteps_alt2();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  MyDslPackage getMyDslPackage();

} //MyDslFactory
