/**
 * generated by Xtext 2.27.0
 */
package org.xtext.example.mydsl10.myDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl10.myDsl.MyDslFactory
 * @model kind="package"
 * @generated
 */
public interface MyDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "myDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl10/MyDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "myDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyDslPackage eINSTANCE = org.xtext.example.mydsl10.myDsl.impl.MyDslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl10.myDsl.impl.PipelineImpl <em>Pipeline</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl10.myDsl.impl.PipelineImpl
   * @see org.xtext.example.mydsl10.myDsl.impl.MyDslPackageImpl#getPipeline()
   * @generated
   */
  int PIPELINE = 0;

  /**
   * The feature id for the '<em><b>Name0</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PIPELINE__NAME0 = 0;

  /**
   * The feature id for the '<em><b>When</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PIPELINE__WHEN = 1;

  /**
   * The feature id for the '<em><b>Trigger</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PIPELINE__TRIGGER = 2;

  /**
   * The feature id for the '<em><b>Pipeline envirnonment</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PIPELINE__PIPELINE_ENVIRNONMENT = 3;

  /**
   * The feature id for the '<em><b>Job</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PIPELINE__JOB = 4;

  /**
   * The number of structural features of the '<em>Pipeline</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PIPELINE_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl10.myDsl.impl.WhenImpl <em>When</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl10.myDsl.impl.WhenImpl
   * @see org.xtext.example.mydsl10.myDsl.impl.MyDslPackageImpl#getWhen()
   * @generated
   */
  int WHEN = 1;

  /**
   * The feature id for the '<em><b>Trigger</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHEN__TRIGGER = 0;

  /**
   * The feature id for the '<em><b>Environment when</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHEN__ENVIRONMENT_WHEN = 1;

  /**
   * The number of structural features of the '<em>When</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHEN_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl10.myDsl.impl.JobIfThenElseImpl <em>Job If Then Else</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl10.myDsl.impl.JobIfThenElseImpl
   * @see org.xtext.example.mydsl10.myDsl.impl.MyDslPackageImpl#getJobIfThenElse()
   * @generated
   */
  int JOB_IF_THEN_ELSE = 2;

  /**
   * The feature id for the '<em><b>Option</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JOB_IF_THEN_ELSE__OPTION = 0;

  /**
   * The number of structural features of the '<em>Job If Then Else</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JOB_IF_THEN_ELSE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl10.myDsl.impl.JobImpl <em>Job</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl10.myDsl.impl.JobImpl
   * @see org.xtext.example.mydsl10.myDsl.impl.MyDslPackageImpl#getJob()
   * @generated
   */
  int JOB = 3;

  /**
   * The feature id for the '<em><b>Allow faillure</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JOB__ALLOW_FAILLURE = 0;

  /**
   * The feature id for the '<em><b>Name1</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JOB__NAME1 = 1;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JOB__DESCRIPTION = 2;

  /**
   * The feature id for the '<em><b>Depends</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JOB__DEPENDS = 3;

  /**
   * The feature id for the '<em><b>Tool framework job</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JOB__TOOL_FRAMEWORK_JOB = 4;

  /**
   * The feature id for the '<em><b>Output</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JOB__OUTPUT = 5;

  /**
   * The feature id for the '<em><b>Ifthenelse</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JOB__IFTHENELSE = 6;

  /**
   * The feature id for the '<em><b>Steps</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JOB__STEPS = 7;

  /**
   * The feature id for the '<em><b>Strategy</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JOB__STRATEGY = 8;

  /**
   * The number of structural features of the '<em>Job</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JOB_FEATURE_COUNT = 9;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl10.myDsl.impl.StrategyImpl <em>Strategy</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl10.myDsl.impl.StrategyImpl
   * @see org.xtext.example.mydsl10.myDsl.impl.MyDslPackageImpl#getStrategy()
   * @generated
   */
  int STRATEGY = 4;

  /**
   * The feature id for the '<em><b>Fail fast</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRATEGY__FAIL_FAST = 0;

  /**
   * The feature id for the '<em><b>Input</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRATEGY__INPUT = 1;

  /**
   * The number of structural features of the '<em>Strategy</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRATEGY_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl10.myDsl.impl.StepsImpl <em>Steps</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl10.myDsl.impl.StepsImpl
   * @see org.xtext.example.mydsl10.myDsl.impl.MyDslPackageImpl#getSteps()
   * @generated
   */
  int STEPS = 5;

  /**
   * The feature id for the '<em><b>Steps</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STEPS__STEPS = 0;

  /**
   * The number of structural features of the '<em>Steps</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STEPS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl10.myDsl.impl.StepOptionsImpl <em>Step Options</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl10.myDsl.impl.StepOptionsImpl
   * @see org.xtext.example.mydsl10.myDsl.impl.MyDslPackageImpl#getStepOptions()
   * @generated
   */
  int STEP_OPTIONS = 6;

  /**
   * The feature id for the '<em><b>Step Option</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STEP_OPTIONS__STEP_OPTION = 0;

  /**
   * The number of structural features of the '<em>Step Options</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STEP_OPTIONS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl10.myDsl.impl.Steps1Impl <em>Steps1</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl10.myDsl.impl.Steps1Impl
   * @see org.xtext.example.mydsl10.myDsl.impl.MyDslPackageImpl#getSteps1()
   * @generated
   */
  int STEPS1 = 7;

  /**
   * The feature id for the '<em><b>Tool framework step</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STEPS1__TOOL_FRAMEWORK_STEP = 0;

  /**
   * The feature id for the '<em><b>Environemnt job</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STEPS1__ENVIRONEMNT_JOB = 1;

  /**
   * The number of structural features of the '<em>Steps1</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STEPS1_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl10.myDsl.impl.Steps2Impl <em>Steps2</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl10.myDsl.impl.Steps2Impl
   * @see org.xtext.example.mydsl10.myDsl.impl.MyDslPackageImpl#getSteps2()
   * @generated
   */
  int STEPS2 = 8;

  /**
   * The feature id for the '<em><b>Depends</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STEPS2__DEPENDS = 0;

  /**
   * The number of structural features of the '<em>Steps2</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STEPS2_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl10.myDsl.impl.Steps3Impl <em>Steps3</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl10.myDsl.impl.Steps3Impl
   * @see org.xtext.example.mydsl10.myDsl.impl.MyDslPackageImpl#getSteps3()
   * @generated
   */
  int STEPS3 = 9;

  /**
   * The feature id for the '<em><b>Command</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STEPS3__COMMAND = 0;

  /**
   * The number of structural features of the '<em>Steps3</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STEPS3_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl10.myDsl.impl.Tool_frameworkImpl <em>Tool framework</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl10.myDsl.impl.Tool_frameworkImpl
   * @see org.xtext.example.mydsl10.myDsl.impl.MyDslPackageImpl#getTool_framework()
   * @generated
   */
  int TOOL_FRAMEWORK = 10;

  /**
   * The feature id for the '<em><b>Name5</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TOOL_FRAMEWORK__NAME5 = 0;

  /**
   * The number of structural features of the '<em>Tool framework</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TOOL_FRAMEWORK_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl10.myDsl.impl.EnvironmentImpl <em>Environment</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl10.myDsl.impl.EnvironmentImpl
   * @see org.xtext.example.mydsl10.myDsl.impl.MyDslPackageImpl#getEnvironment()
   * @generated
   */
  int ENVIRONMENT = 11;

  /**
   * The feature id for the '<em><b>Key</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENVIRONMENT__KEY = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENVIRONMENT__VALUE = 1;

  /**
   * The number of structural features of the '<em>Environment</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENVIRONMENT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl10.myDsl.impl.ArtifactImpl <em>Artifact</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl10.myDsl.impl.ArtifactImpl
   * @see org.xtext.example.mydsl10.myDsl.impl.MyDslPackageImpl#getArtifact()
   * @generated
   */
  int ARTIFACT = 12;

  /**
   * The feature id for the '<em><b>Key</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARTIFACT__KEY = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARTIFACT__VALUE = 1;

  /**
   * The number of structural features of the '<em>Artifact</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARTIFACT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl10.myDsl.impl.CommandImpl <em>Command</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl10.myDsl.impl.CommandImpl
   * @see org.xtext.example.mydsl10.myDsl.impl.MyDslPackageImpl#getCommand()
   * @generated
   */
  int COMMAND = 13;

  /**
   * The number of structural features of the '<em>Command</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl10.myDsl.impl.Command1Impl <em>Command1</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl10.myDsl.impl.Command1Impl
   * @see org.xtext.example.mydsl10.myDsl.impl.MyDslPackageImpl#getCommand1()
   * @generated
   */
  int COMMAND1 = 14;

  /**
   * The feature id for the '<em><b>Tool</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND1__TOOL = COMMAND_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Parameters</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND1__PARAMETERS = COMMAND_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Environment command</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND1__ENVIRONMENT_COMMAND = COMMAND_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Command1</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND1_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl10.myDsl.impl.Command2Impl <em>Command2</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl10.myDsl.impl.Command2Impl
   * @see org.xtext.example.mydsl10.myDsl.impl.MyDslPackageImpl#getCommand2()
   * @generated
   */
  int COMMAND2 = 15;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND2__DESCRIPTION = COMMAND_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Command options</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND2__COMMAND_OPTIONS = COMMAND_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Command2</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND2_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl10.myDsl.impl.Command2EnvImpl <em>Command2 Env</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl10.myDsl.impl.Command2EnvImpl
   * @see org.xtext.example.mydsl10.myDsl.impl.MyDslPackageImpl#getCommand2Env()
   * @generated
   */
  int COMMAND2_ENV = 16;

  /**
   * The feature id for the '<em><b>Environment command</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND2_ENV__ENVIRONMENT_COMMAND = 0;

  /**
   * The number of structural features of the '<em>Command2 Env</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND2_ENV_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl10.myDsl.impl.Command2RunMultipleImpl <em>Command2 Run Multiple</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl10.myDsl.impl.Command2RunMultipleImpl
   * @see org.xtext.example.mydsl10.myDsl.impl.MyDslPackageImpl#getCommand2RunMultiple()
   * @generated
   */
  int COMMAND2_RUN_MULTIPLE = 17;

  /**
   * The feature id for the '<em><b>Parameters</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND2_RUN_MULTIPLE__PARAMETERS = 0;

  /**
   * The number of structural features of the '<em>Command2 Run Multiple</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND2_RUN_MULTIPLE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl10.myDsl.impl.Command2RunOneImpl <em>Command2 Run One</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl10.myDsl.impl.Command2RunOneImpl
   * @see org.xtext.example.mydsl10.myDsl.impl.MyDslPackageImpl#getCommand2RunOne()
   * @generated
   */
  int COMMAND2_RUN_ONE = 18;

  /**
   * The feature id for the '<em><b>Command conditional</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND2_RUN_ONE__COMMAND_CONDITIONAL = 0;

  /**
   * The feature id for the '<em><b>Tool</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND2_RUN_ONE__TOOL = 1;

  /**
   * The feature id for the '<em><b>Parameters</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND2_RUN_ONE__PARAMETERS = 2;

  /**
   * The feature id for the '<em><b>Command string</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND2_RUN_ONE__COMMAND_STRING = 3;

  /**
   * The number of structural features of the '<em>Command2 Run One</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND2_RUN_ONE_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl10.myDsl.impl.Command2UsesImpl <em>Command2 Uses</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl10.myDsl.impl.Command2UsesImpl
   * @see org.xtext.example.mydsl10.myDsl.impl.MyDslPackageImpl#getCommand2Uses()
   * @generated
   */
  int COMMAND2_USES = 19;

  /**
   * The feature id for the '<em><b>Tool</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND2_USES__TOOL = 0;

  /**
   * The number of structural features of the '<em>Command2 Uses</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND2_USES_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl10.myDsl.impl.Command2RunToolImpl <em>Command2 Run Tool</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl10.myDsl.impl.Command2RunToolImpl
   * @see org.xtext.example.mydsl10.myDsl.impl.MyDslPackageImpl#getCommand2RunTool()
   * @generated
   */
  int COMMAND2_RUN_TOOL = 20;

  /**
   * The feature id for the '<em><b>Toolkey</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND2_RUN_TOOL__TOOLKEY = 0;

  /**
   * The feature id for the '<em><b>Parameters</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND2_RUN_TOOL__PARAMETERS = 1;

  /**
   * The number of structural features of the '<em>Command2 Run Tool</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND2_RUN_TOOL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl10.myDsl.impl.IfThenElseImpl <em>If Then Else</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl10.myDsl.impl.IfThenElseImpl
   * @see org.xtext.example.mydsl10.myDsl.impl.MyDslPackageImpl#getIfThenElse()
   * @generated
   */
  int IF_THEN_ELSE = 21;

  /**
   * The feature id for the '<em><b>Alt</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_THEN_ELSE__ALT = 0;

  /**
   * The number of structural features of the '<em>If Then Else</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_THEN_ELSE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl10.myDsl.impl.IfThenElse_alt1Impl <em>If Then Else alt1</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl10.myDsl.impl.IfThenElse_alt1Impl
   * @see org.xtext.example.mydsl10.myDsl.impl.MyDslPackageImpl#getIfThenElse_alt1()
   * @generated
   */
  int IF_THEN_ELSE_ALT1 = 22;

  /**
   * The feature id for the '<em><b>Condition</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_THEN_ELSE_ALT1__CONDITION = 0;

  /**
   * The feature id for the '<em><b>If</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_THEN_ELSE_ALT1__IF = 1;

  /**
   * The feature id for the '<em><b>Else</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_THEN_ELSE_ALT1__ELSE = 2;

  /**
   * The number of structural features of the '<em>If Then Else alt1</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_THEN_ELSE_ALT1_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl10.myDsl.impl.IFThenElseRunImpl <em>IF Then Else Run</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl10.myDsl.impl.IFThenElseRunImpl
   * @see org.xtext.example.mydsl10.myDsl.impl.MyDslPackageImpl#getIFThenElseRun()
   * @generated
   */
  int IF_THEN_ELSE_RUN = 23;

  /**
   * The feature id for the '<em><b>Condition</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_THEN_ELSE_RUN__CONDITION = 0;

  /**
   * The feature id for the '<em><b>If</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_THEN_ELSE_RUN__IF = 1;

  /**
   * The feature id for the '<em><b>Else</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_THEN_ELSE_RUN__ELSE = 2;

  /**
   * The number of structural features of the '<em>IF Then Else Run</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_THEN_ELSE_RUN_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl10.myDsl.impl.IFThenElseStepsImpl <em>IF Then Else Steps</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl10.myDsl.impl.IFThenElseStepsImpl
   * @see org.xtext.example.mydsl10.myDsl.impl.MyDslPackageImpl#getIFThenElseSteps()
   * @generated
   */
  int IF_THEN_ELSE_STEPS = 24;

  /**
   * The feature id for the '<em><b>Alt</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_THEN_ELSE_STEPS__ALT = 0;

  /**
   * The number of structural features of the '<em>IF Then Else Steps</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_THEN_ELSE_STEPS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl10.myDsl.impl.IFThenElseSteps_alt1Impl <em>IF Then Else Steps alt1</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl10.myDsl.impl.IFThenElseSteps_alt1Impl
   * @see org.xtext.example.mydsl10.myDsl.impl.MyDslPackageImpl#getIFThenElseSteps_alt1()
   * @generated
   */
  int IF_THEN_ELSE_STEPS_ALT1 = 25;

  /**
   * The feature id for the '<em><b>Condition</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_THEN_ELSE_STEPS_ALT1__CONDITION = 0;

  /**
   * The feature id for the '<em><b>If</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_THEN_ELSE_STEPS_ALT1__IF = 1;

  /**
   * The feature id for the '<em><b>Elsef</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_THEN_ELSE_STEPS_ALT1__ELSEF = 2;

  /**
   * The number of structural features of the '<em>IF Then Else Steps alt1</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_THEN_ELSE_STEPS_ALT1_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl10.myDsl.impl.IFThenElseJobsSteps_alt2Impl <em>IF Then Else Jobs Steps alt2</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl10.myDsl.impl.IFThenElseJobsSteps_alt2Impl
   * @see org.xtext.example.mydsl10.myDsl.impl.MyDslPackageImpl#getIFThenElseJobsSteps_alt2()
   * @generated
   */
  int IF_THEN_ELSE_JOBS_STEPS_ALT2 = 26;

  /**
   * The feature id for the '<em><b>Condition</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_THEN_ELSE_JOBS_STEPS_ALT2__CONDITION = 0;

  /**
   * The number of structural features of the '<em>IF Then Else Jobs Steps alt2</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_THEN_ELSE_JOBS_STEPS_ALT2_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl10.myDsl.Pipeline <em>Pipeline</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Pipeline</em>'.
   * @see org.xtext.example.mydsl10.myDsl.Pipeline
   * @generated
   */
  EClass getPipeline();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl10.myDsl.Pipeline#getName0 <em>Name0</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name0</em>'.
   * @see org.xtext.example.mydsl10.myDsl.Pipeline#getName0()
   * @see #getPipeline()
   * @generated
   */
  EAttribute getPipeline_Name0();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl10.myDsl.Pipeline#getWhen <em>When</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>When</em>'.
   * @see org.xtext.example.mydsl10.myDsl.Pipeline#getWhen()
   * @see #getPipeline()
   * @generated
   */
  EReference getPipeline_When();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl10.myDsl.Pipeline#getTrigger <em>Trigger</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Trigger</em>'.
   * @see org.xtext.example.mydsl10.myDsl.Pipeline#getTrigger()
   * @see #getPipeline()
   * @generated
   */
  EAttribute getPipeline_Trigger();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl10.myDsl.Pipeline#getPipeline_envirnonment <em>Pipeline envirnonment</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Pipeline envirnonment</em>'.
   * @see org.xtext.example.mydsl10.myDsl.Pipeline#getPipeline_envirnonment()
   * @see #getPipeline()
   * @generated
   */
  EReference getPipeline_Pipeline_envirnonment();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl10.myDsl.Pipeline#getJob <em>Job</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Job</em>'.
   * @see org.xtext.example.mydsl10.myDsl.Pipeline#getJob()
   * @see #getPipeline()
   * @generated
   */
  EReference getPipeline_Job();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl10.myDsl.When <em>When</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>When</em>'.
   * @see org.xtext.example.mydsl10.myDsl.When
   * @generated
   */
  EClass getWhen();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl10.myDsl.When#getTrigger <em>Trigger</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Trigger</em>'.
   * @see org.xtext.example.mydsl10.myDsl.When#getTrigger()
   * @see #getWhen()
   * @generated
   */
  EAttribute getWhen_Trigger();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl10.myDsl.When#getEnvironment_when <em>Environment when</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Environment when</em>'.
   * @see org.xtext.example.mydsl10.myDsl.When#getEnvironment_when()
   * @see #getWhen()
   * @generated
   */
  EReference getWhen_Environment_when();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl10.myDsl.JobIfThenElse <em>Job If Then Else</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Job If Then Else</em>'.
   * @see org.xtext.example.mydsl10.myDsl.JobIfThenElse
   * @generated
   */
  EClass getJobIfThenElse();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl10.myDsl.JobIfThenElse#getOption <em>Option</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Option</em>'.
   * @see org.xtext.example.mydsl10.myDsl.JobIfThenElse#getOption()
   * @see #getJobIfThenElse()
   * @generated
   */
  EReference getJobIfThenElse_Option();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl10.myDsl.Job <em>Job</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Job</em>'.
   * @see org.xtext.example.mydsl10.myDsl.Job
   * @generated
   */
  EClass getJob();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl10.myDsl.Job#isAllow_faillure <em>Allow faillure</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Allow faillure</em>'.
   * @see org.xtext.example.mydsl10.myDsl.Job#isAllow_faillure()
   * @see #getJob()
   * @generated
   */
  EAttribute getJob_Allow_faillure();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl10.myDsl.Job#getName1 <em>Name1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name1</em>'.
   * @see org.xtext.example.mydsl10.myDsl.Job#getName1()
   * @see #getJob()
   * @generated
   */
  EAttribute getJob_Name1();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.example.mydsl10.myDsl.Job#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Description</em>'.
   * @see org.xtext.example.mydsl10.myDsl.Job#getDescription()
   * @see #getJob()
   * @generated
   */
  EAttribute getJob_Description();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl10.myDsl.Job#getDepends <em>Depends</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Depends</em>'.
   * @see org.xtext.example.mydsl10.myDsl.Job#getDepends()
   * @see #getJob()
   * @generated
   */
  EReference getJob_Depends();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl10.myDsl.Job#getTool_framework_job <em>Tool framework job</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Tool framework job</em>'.
   * @see org.xtext.example.mydsl10.myDsl.Job#getTool_framework_job()
   * @see #getJob()
   * @generated
   */
  EReference getJob_Tool_framework_job();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl10.myDsl.Job#getOutput <em>Output</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Output</em>'.
   * @see org.xtext.example.mydsl10.myDsl.Job#getOutput()
   * @see #getJob()
   * @generated
   */
  EReference getJob_Output();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl10.myDsl.Job#getIfthenelse <em>Ifthenelse</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Ifthenelse</em>'.
   * @see org.xtext.example.mydsl10.myDsl.Job#getIfthenelse()
   * @see #getJob()
   * @generated
   */
  EReference getJob_Ifthenelse();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl10.myDsl.Job#getSteps <em>Steps</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Steps</em>'.
   * @see org.xtext.example.mydsl10.myDsl.Job#getSteps()
   * @see #getJob()
   * @generated
   */
  EReference getJob_Steps();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl10.myDsl.Job#getStrategy <em>Strategy</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Strategy</em>'.
   * @see org.xtext.example.mydsl10.myDsl.Job#getStrategy()
   * @see #getJob()
   * @generated
   */
  EReference getJob_Strategy();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl10.myDsl.Strategy <em>Strategy</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Strategy</em>'.
   * @see org.xtext.example.mydsl10.myDsl.Strategy
   * @generated
   */
  EClass getStrategy();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl10.myDsl.Strategy#getFail_fast <em>Fail fast</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Fail fast</em>'.
   * @see org.xtext.example.mydsl10.myDsl.Strategy#getFail_fast()
   * @see #getStrategy()
   * @generated
   */
  EAttribute getStrategy_Fail_fast();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl10.myDsl.Strategy#getInput <em>Input</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Input</em>'.
   * @see org.xtext.example.mydsl10.myDsl.Strategy#getInput()
   * @see #getStrategy()
   * @generated
   */
  EReference getStrategy_Input();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl10.myDsl.Steps <em>Steps</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Steps</em>'.
   * @see org.xtext.example.mydsl10.myDsl.Steps
   * @generated
   */
  EClass getSteps();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl10.myDsl.Steps#getSteps <em>Steps</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Steps</em>'.
   * @see org.xtext.example.mydsl10.myDsl.Steps#getSteps()
   * @see #getSteps()
   * @generated
   */
  EReference getSteps_Steps();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl10.myDsl.StepOptions <em>Step Options</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Step Options</em>'.
   * @see org.xtext.example.mydsl10.myDsl.StepOptions
   * @generated
   */
  EClass getStepOptions();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl10.myDsl.StepOptions#getStepOption <em>Step Option</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Step Option</em>'.
   * @see org.xtext.example.mydsl10.myDsl.StepOptions#getStepOption()
   * @see #getStepOptions()
   * @generated
   */
  EReference getStepOptions_StepOption();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl10.myDsl.Steps1 <em>Steps1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Steps1</em>'.
   * @see org.xtext.example.mydsl10.myDsl.Steps1
   * @generated
   */
  EClass getSteps1();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl10.myDsl.Steps1#getTool_framework_step <em>Tool framework step</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Tool framework step</em>'.
   * @see org.xtext.example.mydsl10.myDsl.Steps1#getTool_framework_step()
   * @see #getSteps1()
   * @generated
   */
  EReference getSteps1_Tool_framework_step();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl10.myDsl.Steps1#getEnvironemnt_job <em>Environemnt job</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Environemnt job</em>'.
   * @see org.xtext.example.mydsl10.myDsl.Steps1#getEnvironemnt_job()
   * @see #getSteps1()
   * @generated
   */
  EReference getSteps1_Environemnt_job();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl10.myDsl.Steps2 <em>Steps2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Steps2</em>'.
   * @see org.xtext.example.mydsl10.myDsl.Steps2
   * @generated
   */
  EClass getSteps2();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl10.myDsl.Steps2#getDepends <em>Depends</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Depends</em>'.
   * @see org.xtext.example.mydsl10.myDsl.Steps2#getDepends()
   * @see #getSteps2()
   * @generated
   */
  EReference getSteps2_Depends();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl10.myDsl.Steps3 <em>Steps3</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Steps3</em>'.
   * @see org.xtext.example.mydsl10.myDsl.Steps3
   * @generated
   */
  EClass getSteps3();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl10.myDsl.Steps3#getCommand <em>Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Command</em>'.
   * @see org.xtext.example.mydsl10.myDsl.Steps3#getCommand()
   * @see #getSteps3()
   * @generated
   */
  EReference getSteps3_Command();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl10.myDsl.Tool_framework <em>Tool framework</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Tool framework</em>'.
   * @see org.xtext.example.mydsl10.myDsl.Tool_framework
   * @generated
   */
  EClass getTool_framework();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl10.myDsl.Tool_framework#getName5 <em>Name5</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name5</em>'.
   * @see org.xtext.example.mydsl10.myDsl.Tool_framework#getName5()
   * @see #getTool_framework()
   * @generated
   */
  EAttribute getTool_framework_Name5();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl10.myDsl.Environment <em>Environment</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Environment</em>'.
   * @see org.xtext.example.mydsl10.myDsl.Environment
   * @generated
   */
  EClass getEnvironment();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl10.myDsl.Environment#getKey <em>Key</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Key</em>'.
   * @see org.xtext.example.mydsl10.myDsl.Environment#getKey()
   * @see #getEnvironment()
   * @generated
   */
  EAttribute getEnvironment_Key();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl10.myDsl.Environment#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.example.mydsl10.myDsl.Environment#getValue()
   * @see #getEnvironment()
   * @generated
   */
  EAttribute getEnvironment_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl10.myDsl.Artifact <em>Artifact</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Artifact</em>'.
   * @see org.xtext.example.mydsl10.myDsl.Artifact
   * @generated
   */
  EClass getArtifact();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl10.myDsl.Artifact#getKey <em>Key</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Key</em>'.
   * @see org.xtext.example.mydsl10.myDsl.Artifact#getKey()
   * @see #getArtifact()
   * @generated
   */
  EAttribute getArtifact_Key();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl10.myDsl.Artifact#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.example.mydsl10.myDsl.Artifact#getValue()
   * @see #getArtifact()
   * @generated
   */
  EAttribute getArtifact_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl10.myDsl.Command <em>Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Command</em>'.
   * @see org.xtext.example.mydsl10.myDsl.Command
   * @generated
   */
  EClass getCommand();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl10.myDsl.Command1 <em>Command1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Command1</em>'.
   * @see org.xtext.example.mydsl10.myDsl.Command1
   * @generated
   */
  EClass getCommand1();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl10.myDsl.Command1#getTool <em>Tool</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Tool</em>'.
   * @see org.xtext.example.mydsl10.myDsl.Command1#getTool()
   * @see #getCommand1()
   * @generated
   */
  EReference getCommand1_Tool();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.example.mydsl10.myDsl.Command1#getParameters <em>Parameters</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Parameters</em>'.
   * @see org.xtext.example.mydsl10.myDsl.Command1#getParameters()
   * @see #getCommand1()
   * @generated
   */
  EAttribute getCommand1_Parameters();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl10.myDsl.Command1#getEnvironment_command <em>Environment command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Environment command</em>'.
   * @see org.xtext.example.mydsl10.myDsl.Command1#getEnvironment_command()
   * @see #getCommand1()
   * @generated
   */
  EReference getCommand1_Environment_command();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl10.myDsl.Command2 <em>Command2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Command2</em>'.
   * @see org.xtext.example.mydsl10.myDsl.Command2
   * @generated
   */
  EClass getCommand2();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.example.mydsl10.myDsl.Command2#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Description</em>'.
   * @see org.xtext.example.mydsl10.myDsl.Command2#getDescription()
   * @see #getCommand2()
   * @generated
   */
  EAttribute getCommand2_Description();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl10.myDsl.Command2#getCommand_options <em>Command options</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Command options</em>'.
   * @see org.xtext.example.mydsl10.myDsl.Command2#getCommand_options()
   * @see #getCommand2()
   * @generated
   */
  EReference getCommand2_Command_options();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl10.myDsl.Command2Env <em>Command2 Env</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Command2 Env</em>'.
   * @see org.xtext.example.mydsl10.myDsl.Command2Env
   * @generated
   */
  EClass getCommand2Env();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl10.myDsl.Command2Env#getEnvironment_command <em>Environment command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Environment command</em>'.
   * @see org.xtext.example.mydsl10.myDsl.Command2Env#getEnvironment_command()
   * @see #getCommand2Env()
   * @generated
   */
  EReference getCommand2Env_Environment_command();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl10.myDsl.Command2RunMultiple <em>Command2 Run Multiple</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Command2 Run Multiple</em>'.
   * @see org.xtext.example.mydsl10.myDsl.Command2RunMultiple
   * @generated
   */
  EClass getCommand2RunMultiple();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.example.mydsl10.myDsl.Command2RunMultiple#getParameters <em>Parameters</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Parameters</em>'.
   * @see org.xtext.example.mydsl10.myDsl.Command2RunMultiple#getParameters()
   * @see #getCommand2RunMultiple()
   * @generated
   */
  EAttribute getCommand2RunMultiple_Parameters();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl10.myDsl.Command2RunOne <em>Command2 Run One</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Command2 Run One</em>'.
   * @see org.xtext.example.mydsl10.myDsl.Command2RunOne
   * @generated
   */
  EClass getCommand2RunOne();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl10.myDsl.Command2RunOne#getCommand_conditional <em>Command conditional</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Command conditional</em>'.
   * @see org.xtext.example.mydsl10.myDsl.Command2RunOne#getCommand_conditional()
   * @see #getCommand2RunOne()
   * @generated
   */
  EReference getCommand2RunOne_Command_conditional();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl10.myDsl.Command2RunOne#getTool <em>Tool</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Tool</em>'.
   * @see org.xtext.example.mydsl10.myDsl.Command2RunOne#getTool()
   * @see #getCommand2RunOne()
   * @generated
   */
  EReference getCommand2RunOne_Tool();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.example.mydsl10.myDsl.Command2RunOne#getParameters <em>Parameters</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Parameters</em>'.
   * @see org.xtext.example.mydsl10.myDsl.Command2RunOne#getParameters()
   * @see #getCommand2RunOne()
   * @generated
   */
  EAttribute getCommand2RunOne_Parameters();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.example.mydsl10.myDsl.Command2RunOne#getCommand_string <em>Command string</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Command string</em>'.
   * @see org.xtext.example.mydsl10.myDsl.Command2RunOne#getCommand_string()
   * @see #getCommand2RunOne()
   * @generated
   */
  EAttribute getCommand2RunOne_Command_string();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl10.myDsl.Command2Uses <em>Command2 Uses</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Command2 Uses</em>'.
   * @see org.xtext.example.mydsl10.myDsl.Command2Uses
   * @generated
   */
  EClass getCommand2Uses();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl10.myDsl.Command2Uses#getTool <em>Tool</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Tool</em>'.
   * @see org.xtext.example.mydsl10.myDsl.Command2Uses#getTool()
   * @see #getCommand2Uses()
   * @generated
   */
  EReference getCommand2Uses_Tool();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl10.myDsl.Command2RunTool <em>Command2 Run Tool</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Command2 Run Tool</em>'.
   * @see org.xtext.example.mydsl10.myDsl.Command2RunTool
   * @generated
   */
  EClass getCommand2RunTool();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.example.mydsl10.myDsl.Command2RunTool#getToolkey <em>Toolkey</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Toolkey</em>'.
   * @see org.xtext.example.mydsl10.myDsl.Command2RunTool#getToolkey()
   * @see #getCommand2RunTool()
   * @generated
   */
  EAttribute getCommand2RunTool_Toolkey();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.example.mydsl10.myDsl.Command2RunTool#getParameters <em>Parameters</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Parameters</em>'.
   * @see org.xtext.example.mydsl10.myDsl.Command2RunTool#getParameters()
   * @see #getCommand2RunTool()
   * @generated
   */
  EAttribute getCommand2RunTool_Parameters();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl10.myDsl.IfThenElse <em>If Then Else</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>If Then Else</em>'.
   * @see org.xtext.example.mydsl10.myDsl.IfThenElse
   * @generated
   */
  EClass getIfThenElse();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl10.myDsl.IfThenElse#getAlt <em>Alt</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Alt</em>'.
   * @see org.xtext.example.mydsl10.myDsl.IfThenElse#getAlt()
   * @see #getIfThenElse()
   * @generated
   */
  EReference getIfThenElse_Alt();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl10.myDsl.IfThenElse_alt1 <em>If Then Else alt1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>If Then Else alt1</em>'.
   * @see org.xtext.example.mydsl10.myDsl.IfThenElse_alt1
   * @generated
   */
  EClass getIfThenElse_alt1();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl10.myDsl.IfThenElse_alt1#getCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Condition</em>'.
   * @see org.xtext.example.mydsl10.myDsl.IfThenElse_alt1#getCondition()
   * @see #getIfThenElse_alt1()
   * @generated
   */
  EAttribute getIfThenElse_alt1_Condition();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl10.myDsl.IfThenElse_alt1#getIf <em>If</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>If</em>'.
   * @see org.xtext.example.mydsl10.myDsl.IfThenElse_alt1#getIf()
   * @see #getIfThenElse_alt1()
   * @generated
   */
  EReference getIfThenElse_alt1_If();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl10.myDsl.IfThenElse_alt1#getElse <em>Else</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Else</em>'.
   * @see org.xtext.example.mydsl10.myDsl.IfThenElse_alt1#getElse()
   * @see #getIfThenElse_alt1()
   * @generated
   */
  EReference getIfThenElse_alt1_Else();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl10.myDsl.IFThenElseRun <em>IF Then Else Run</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>IF Then Else Run</em>'.
   * @see org.xtext.example.mydsl10.myDsl.IFThenElseRun
   * @generated
   */
  EClass getIFThenElseRun();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl10.myDsl.IFThenElseRun#getCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Condition</em>'.
   * @see org.xtext.example.mydsl10.myDsl.IFThenElseRun#getCondition()
   * @see #getIFThenElseRun()
   * @generated
   */
  EAttribute getIFThenElseRun_Condition();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl10.myDsl.IFThenElseRun#getIf <em>If</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>If</em>'.
   * @see org.xtext.example.mydsl10.myDsl.IFThenElseRun#getIf()
   * @see #getIFThenElseRun()
   * @generated
   */
  EAttribute getIFThenElseRun_If();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl10.myDsl.IFThenElseRun#getElse <em>Else</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Else</em>'.
   * @see org.xtext.example.mydsl10.myDsl.IFThenElseRun#getElse()
   * @see #getIFThenElseRun()
   * @generated
   */
  EAttribute getIFThenElseRun_Else();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl10.myDsl.IFThenElseSteps <em>IF Then Else Steps</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>IF Then Else Steps</em>'.
   * @see org.xtext.example.mydsl10.myDsl.IFThenElseSteps
   * @generated
   */
  EClass getIFThenElseSteps();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl10.myDsl.IFThenElseSteps#getAlt <em>Alt</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Alt</em>'.
   * @see org.xtext.example.mydsl10.myDsl.IFThenElseSteps#getAlt()
   * @see #getIFThenElseSteps()
   * @generated
   */
  EReference getIFThenElseSteps_Alt();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl10.myDsl.IFThenElseSteps_alt1 <em>IF Then Else Steps alt1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>IF Then Else Steps alt1</em>'.
   * @see org.xtext.example.mydsl10.myDsl.IFThenElseSteps_alt1
   * @generated
   */
  EClass getIFThenElseSteps_alt1();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl10.myDsl.IFThenElseSteps_alt1#getCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Condition</em>'.
   * @see org.xtext.example.mydsl10.myDsl.IFThenElseSteps_alt1#getCondition()
   * @see #getIFThenElseSteps_alt1()
   * @generated
   */
  EAttribute getIFThenElseSteps_alt1_Condition();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl10.myDsl.IFThenElseSteps_alt1#getIf <em>If</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>If</em>'.
   * @see org.xtext.example.mydsl10.myDsl.IFThenElseSteps_alt1#getIf()
   * @see #getIFThenElseSteps_alt1()
   * @generated
   */
  EReference getIFThenElseSteps_alt1_If();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl10.myDsl.IFThenElseSteps_alt1#getElsef <em>Elsef</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elsef</em>'.
   * @see org.xtext.example.mydsl10.myDsl.IFThenElseSteps_alt1#getElsef()
   * @see #getIFThenElseSteps_alt1()
   * @generated
   */
  EReference getIFThenElseSteps_alt1_Elsef();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl10.myDsl.IFThenElseJobsSteps_alt2 <em>IF Then Else Jobs Steps alt2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>IF Then Else Jobs Steps alt2</em>'.
   * @see org.xtext.example.mydsl10.myDsl.IFThenElseJobsSteps_alt2
   * @generated
   */
  EClass getIFThenElseJobsSteps_alt2();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl10.myDsl.IFThenElseJobsSteps_alt2#getCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Condition</em>'.
   * @see org.xtext.example.mydsl10.myDsl.IFThenElseJobsSteps_alt2#getCondition()
   * @see #getIFThenElseJobsSteps_alt2()
   * @generated
   */
  EAttribute getIFThenElseJobsSteps_alt2_Condition();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MyDslFactory getMyDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl10.myDsl.impl.PipelineImpl <em>Pipeline</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl10.myDsl.impl.PipelineImpl
     * @see org.xtext.example.mydsl10.myDsl.impl.MyDslPackageImpl#getPipeline()
     * @generated
     */
    EClass PIPELINE = eINSTANCE.getPipeline();

    /**
     * The meta object literal for the '<em><b>Name0</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PIPELINE__NAME0 = eINSTANCE.getPipeline_Name0();

    /**
     * The meta object literal for the '<em><b>When</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PIPELINE__WHEN = eINSTANCE.getPipeline_When();

    /**
     * The meta object literal for the '<em><b>Trigger</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PIPELINE__TRIGGER = eINSTANCE.getPipeline_Trigger();

    /**
     * The meta object literal for the '<em><b>Pipeline envirnonment</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PIPELINE__PIPELINE_ENVIRNONMENT = eINSTANCE.getPipeline_Pipeline_envirnonment();

    /**
     * The meta object literal for the '<em><b>Job</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PIPELINE__JOB = eINSTANCE.getPipeline_Job();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl10.myDsl.impl.WhenImpl <em>When</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl10.myDsl.impl.WhenImpl
     * @see org.xtext.example.mydsl10.myDsl.impl.MyDslPackageImpl#getWhen()
     * @generated
     */
    EClass WHEN = eINSTANCE.getWhen();

    /**
     * The meta object literal for the '<em><b>Trigger</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WHEN__TRIGGER = eINSTANCE.getWhen_Trigger();

    /**
     * The meta object literal for the '<em><b>Environment when</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WHEN__ENVIRONMENT_WHEN = eINSTANCE.getWhen_Environment_when();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl10.myDsl.impl.JobIfThenElseImpl <em>Job If Then Else</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl10.myDsl.impl.JobIfThenElseImpl
     * @see org.xtext.example.mydsl10.myDsl.impl.MyDslPackageImpl#getJobIfThenElse()
     * @generated
     */
    EClass JOB_IF_THEN_ELSE = eINSTANCE.getJobIfThenElse();

    /**
     * The meta object literal for the '<em><b>Option</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JOB_IF_THEN_ELSE__OPTION = eINSTANCE.getJobIfThenElse_Option();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl10.myDsl.impl.JobImpl <em>Job</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl10.myDsl.impl.JobImpl
     * @see org.xtext.example.mydsl10.myDsl.impl.MyDslPackageImpl#getJob()
     * @generated
     */
    EClass JOB = eINSTANCE.getJob();

    /**
     * The meta object literal for the '<em><b>Allow faillure</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute JOB__ALLOW_FAILLURE = eINSTANCE.getJob_Allow_faillure();

    /**
     * The meta object literal for the '<em><b>Name1</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute JOB__NAME1 = eINSTANCE.getJob_Name1();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute JOB__DESCRIPTION = eINSTANCE.getJob_Description();

    /**
     * The meta object literal for the '<em><b>Depends</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JOB__DEPENDS = eINSTANCE.getJob_Depends();

    /**
     * The meta object literal for the '<em><b>Tool framework job</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JOB__TOOL_FRAMEWORK_JOB = eINSTANCE.getJob_Tool_framework_job();

    /**
     * The meta object literal for the '<em><b>Output</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JOB__OUTPUT = eINSTANCE.getJob_Output();

    /**
     * The meta object literal for the '<em><b>Ifthenelse</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JOB__IFTHENELSE = eINSTANCE.getJob_Ifthenelse();

    /**
     * The meta object literal for the '<em><b>Steps</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JOB__STEPS = eINSTANCE.getJob_Steps();

    /**
     * The meta object literal for the '<em><b>Strategy</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JOB__STRATEGY = eINSTANCE.getJob_Strategy();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl10.myDsl.impl.StrategyImpl <em>Strategy</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl10.myDsl.impl.StrategyImpl
     * @see org.xtext.example.mydsl10.myDsl.impl.MyDslPackageImpl#getStrategy()
     * @generated
     */
    EClass STRATEGY = eINSTANCE.getStrategy();

    /**
     * The meta object literal for the '<em><b>Fail fast</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STRATEGY__FAIL_FAST = eINSTANCE.getStrategy_Fail_fast();

    /**
     * The meta object literal for the '<em><b>Input</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STRATEGY__INPUT = eINSTANCE.getStrategy_Input();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl10.myDsl.impl.StepsImpl <em>Steps</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl10.myDsl.impl.StepsImpl
     * @see org.xtext.example.mydsl10.myDsl.impl.MyDslPackageImpl#getSteps()
     * @generated
     */
    EClass STEPS = eINSTANCE.getSteps();

    /**
     * The meta object literal for the '<em><b>Steps</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STEPS__STEPS = eINSTANCE.getSteps_Steps();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl10.myDsl.impl.StepOptionsImpl <em>Step Options</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl10.myDsl.impl.StepOptionsImpl
     * @see org.xtext.example.mydsl10.myDsl.impl.MyDslPackageImpl#getStepOptions()
     * @generated
     */
    EClass STEP_OPTIONS = eINSTANCE.getStepOptions();

    /**
     * The meta object literal for the '<em><b>Step Option</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STEP_OPTIONS__STEP_OPTION = eINSTANCE.getStepOptions_StepOption();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl10.myDsl.impl.Steps1Impl <em>Steps1</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl10.myDsl.impl.Steps1Impl
     * @see org.xtext.example.mydsl10.myDsl.impl.MyDslPackageImpl#getSteps1()
     * @generated
     */
    EClass STEPS1 = eINSTANCE.getSteps1();

    /**
     * The meta object literal for the '<em><b>Tool framework step</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STEPS1__TOOL_FRAMEWORK_STEP = eINSTANCE.getSteps1_Tool_framework_step();

    /**
     * The meta object literal for the '<em><b>Environemnt job</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STEPS1__ENVIRONEMNT_JOB = eINSTANCE.getSteps1_Environemnt_job();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl10.myDsl.impl.Steps2Impl <em>Steps2</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl10.myDsl.impl.Steps2Impl
     * @see org.xtext.example.mydsl10.myDsl.impl.MyDslPackageImpl#getSteps2()
     * @generated
     */
    EClass STEPS2 = eINSTANCE.getSteps2();

    /**
     * The meta object literal for the '<em><b>Depends</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STEPS2__DEPENDS = eINSTANCE.getSteps2_Depends();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl10.myDsl.impl.Steps3Impl <em>Steps3</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl10.myDsl.impl.Steps3Impl
     * @see org.xtext.example.mydsl10.myDsl.impl.MyDslPackageImpl#getSteps3()
     * @generated
     */
    EClass STEPS3 = eINSTANCE.getSteps3();

    /**
     * The meta object literal for the '<em><b>Command</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STEPS3__COMMAND = eINSTANCE.getSteps3_Command();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl10.myDsl.impl.Tool_frameworkImpl <em>Tool framework</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl10.myDsl.impl.Tool_frameworkImpl
     * @see org.xtext.example.mydsl10.myDsl.impl.MyDslPackageImpl#getTool_framework()
     * @generated
     */
    EClass TOOL_FRAMEWORK = eINSTANCE.getTool_framework();

    /**
     * The meta object literal for the '<em><b>Name5</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TOOL_FRAMEWORK__NAME5 = eINSTANCE.getTool_framework_Name5();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl10.myDsl.impl.EnvironmentImpl <em>Environment</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl10.myDsl.impl.EnvironmentImpl
     * @see org.xtext.example.mydsl10.myDsl.impl.MyDslPackageImpl#getEnvironment()
     * @generated
     */
    EClass ENVIRONMENT = eINSTANCE.getEnvironment();

    /**
     * The meta object literal for the '<em><b>Key</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENVIRONMENT__KEY = eINSTANCE.getEnvironment_Key();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENVIRONMENT__VALUE = eINSTANCE.getEnvironment_Value();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl10.myDsl.impl.ArtifactImpl <em>Artifact</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl10.myDsl.impl.ArtifactImpl
     * @see org.xtext.example.mydsl10.myDsl.impl.MyDslPackageImpl#getArtifact()
     * @generated
     */
    EClass ARTIFACT = eINSTANCE.getArtifact();

    /**
     * The meta object literal for the '<em><b>Key</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ARTIFACT__KEY = eINSTANCE.getArtifact_Key();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ARTIFACT__VALUE = eINSTANCE.getArtifact_Value();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl10.myDsl.impl.CommandImpl <em>Command</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl10.myDsl.impl.CommandImpl
     * @see org.xtext.example.mydsl10.myDsl.impl.MyDslPackageImpl#getCommand()
     * @generated
     */
    EClass COMMAND = eINSTANCE.getCommand();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl10.myDsl.impl.Command1Impl <em>Command1</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl10.myDsl.impl.Command1Impl
     * @see org.xtext.example.mydsl10.myDsl.impl.MyDslPackageImpl#getCommand1()
     * @generated
     */
    EClass COMMAND1 = eINSTANCE.getCommand1();

    /**
     * The meta object literal for the '<em><b>Tool</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMMAND1__TOOL = eINSTANCE.getCommand1_Tool();

    /**
     * The meta object literal for the '<em><b>Parameters</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMMAND1__PARAMETERS = eINSTANCE.getCommand1_Parameters();

    /**
     * The meta object literal for the '<em><b>Environment command</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMMAND1__ENVIRONMENT_COMMAND = eINSTANCE.getCommand1_Environment_command();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl10.myDsl.impl.Command2Impl <em>Command2</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl10.myDsl.impl.Command2Impl
     * @see org.xtext.example.mydsl10.myDsl.impl.MyDslPackageImpl#getCommand2()
     * @generated
     */
    EClass COMMAND2 = eINSTANCE.getCommand2();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMMAND2__DESCRIPTION = eINSTANCE.getCommand2_Description();

    /**
     * The meta object literal for the '<em><b>Command options</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMMAND2__COMMAND_OPTIONS = eINSTANCE.getCommand2_Command_options();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl10.myDsl.impl.Command2EnvImpl <em>Command2 Env</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl10.myDsl.impl.Command2EnvImpl
     * @see org.xtext.example.mydsl10.myDsl.impl.MyDslPackageImpl#getCommand2Env()
     * @generated
     */
    EClass COMMAND2_ENV = eINSTANCE.getCommand2Env();

    /**
     * The meta object literal for the '<em><b>Environment command</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMMAND2_ENV__ENVIRONMENT_COMMAND = eINSTANCE.getCommand2Env_Environment_command();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl10.myDsl.impl.Command2RunMultipleImpl <em>Command2 Run Multiple</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl10.myDsl.impl.Command2RunMultipleImpl
     * @see org.xtext.example.mydsl10.myDsl.impl.MyDslPackageImpl#getCommand2RunMultiple()
     * @generated
     */
    EClass COMMAND2_RUN_MULTIPLE = eINSTANCE.getCommand2RunMultiple();

    /**
     * The meta object literal for the '<em><b>Parameters</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMMAND2_RUN_MULTIPLE__PARAMETERS = eINSTANCE.getCommand2RunMultiple_Parameters();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl10.myDsl.impl.Command2RunOneImpl <em>Command2 Run One</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl10.myDsl.impl.Command2RunOneImpl
     * @see org.xtext.example.mydsl10.myDsl.impl.MyDslPackageImpl#getCommand2RunOne()
     * @generated
     */
    EClass COMMAND2_RUN_ONE = eINSTANCE.getCommand2RunOne();

    /**
     * The meta object literal for the '<em><b>Command conditional</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMMAND2_RUN_ONE__COMMAND_CONDITIONAL = eINSTANCE.getCommand2RunOne_Command_conditional();

    /**
     * The meta object literal for the '<em><b>Tool</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMMAND2_RUN_ONE__TOOL = eINSTANCE.getCommand2RunOne_Tool();

    /**
     * The meta object literal for the '<em><b>Parameters</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMMAND2_RUN_ONE__PARAMETERS = eINSTANCE.getCommand2RunOne_Parameters();

    /**
     * The meta object literal for the '<em><b>Command string</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMMAND2_RUN_ONE__COMMAND_STRING = eINSTANCE.getCommand2RunOne_Command_string();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl10.myDsl.impl.Command2UsesImpl <em>Command2 Uses</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl10.myDsl.impl.Command2UsesImpl
     * @see org.xtext.example.mydsl10.myDsl.impl.MyDslPackageImpl#getCommand2Uses()
     * @generated
     */
    EClass COMMAND2_USES = eINSTANCE.getCommand2Uses();

    /**
     * The meta object literal for the '<em><b>Tool</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMMAND2_USES__TOOL = eINSTANCE.getCommand2Uses_Tool();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl10.myDsl.impl.Command2RunToolImpl <em>Command2 Run Tool</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl10.myDsl.impl.Command2RunToolImpl
     * @see org.xtext.example.mydsl10.myDsl.impl.MyDslPackageImpl#getCommand2RunTool()
     * @generated
     */
    EClass COMMAND2_RUN_TOOL = eINSTANCE.getCommand2RunTool();

    /**
     * The meta object literal for the '<em><b>Toolkey</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMMAND2_RUN_TOOL__TOOLKEY = eINSTANCE.getCommand2RunTool_Toolkey();

    /**
     * The meta object literal for the '<em><b>Parameters</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMMAND2_RUN_TOOL__PARAMETERS = eINSTANCE.getCommand2RunTool_Parameters();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl10.myDsl.impl.IfThenElseImpl <em>If Then Else</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl10.myDsl.impl.IfThenElseImpl
     * @see org.xtext.example.mydsl10.myDsl.impl.MyDslPackageImpl#getIfThenElse()
     * @generated
     */
    EClass IF_THEN_ELSE = eINSTANCE.getIfThenElse();

    /**
     * The meta object literal for the '<em><b>Alt</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IF_THEN_ELSE__ALT = eINSTANCE.getIfThenElse_Alt();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl10.myDsl.impl.IfThenElse_alt1Impl <em>If Then Else alt1</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl10.myDsl.impl.IfThenElse_alt1Impl
     * @see org.xtext.example.mydsl10.myDsl.impl.MyDslPackageImpl#getIfThenElse_alt1()
     * @generated
     */
    EClass IF_THEN_ELSE_ALT1 = eINSTANCE.getIfThenElse_alt1();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IF_THEN_ELSE_ALT1__CONDITION = eINSTANCE.getIfThenElse_alt1_Condition();

    /**
     * The meta object literal for the '<em><b>If</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IF_THEN_ELSE_ALT1__IF = eINSTANCE.getIfThenElse_alt1_If();

    /**
     * The meta object literal for the '<em><b>Else</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IF_THEN_ELSE_ALT1__ELSE = eINSTANCE.getIfThenElse_alt1_Else();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl10.myDsl.impl.IFThenElseRunImpl <em>IF Then Else Run</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl10.myDsl.impl.IFThenElseRunImpl
     * @see org.xtext.example.mydsl10.myDsl.impl.MyDslPackageImpl#getIFThenElseRun()
     * @generated
     */
    EClass IF_THEN_ELSE_RUN = eINSTANCE.getIFThenElseRun();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IF_THEN_ELSE_RUN__CONDITION = eINSTANCE.getIFThenElseRun_Condition();

    /**
     * The meta object literal for the '<em><b>If</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IF_THEN_ELSE_RUN__IF = eINSTANCE.getIFThenElseRun_If();

    /**
     * The meta object literal for the '<em><b>Else</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IF_THEN_ELSE_RUN__ELSE = eINSTANCE.getIFThenElseRun_Else();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl10.myDsl.impl.IFThenElseStepsImpl <em>IF Then Else Steps</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl10.myDsl.impl.IFThenElseStepsImpl
     * @see org.xtext.example.mydsl10.myDsl.impl.MyDslPackageImpl#getIFThenElseSteps()
     * @generated
     */
    EClass IF_THEN_ELSE_STEPS = eINSTANCE.getIFThenElseSteps();

    /**
     * The meta object literal for the '<em><b>Alt</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IF_THEN_ELSE_STEPS__ALT = eINSTANCE.getIFThenElseSteps_Alt();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl10.myDsl.impl.IFThenElseSteps_alt1Impl <em>IF Then Else Steps alt1</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl10.myDsl.impl.IFThenElseSteps_alt1Impl
     * @see org.xtext.example.mydsl10.myDsl.impl.MyDslPackageImpl#getIFThenElseSteps_alt1()
     * @generated
     */
    EClass IF_THEN_ELSE_STEPS_ALT1 = eINSTANCE.getIFThenElseSteps_alt1();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IF_THEN_ELSE_STEPS_ALT1__CONDITION = eINSTANCE.getIFThenElseSteps_alt1_Condition();

    /**
     * The meta object literal for the '<em><b>If</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IF_THEN_ELSE_STEPS_ALT1__IF = eINSTANCE.getIFThenElseSteps_alt1_If();

    /**
     * The meta object literal for the '<em><b>Elsef</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IF_THEN_ELSE_STEPS_ALT1__ELSEF = eINSTANCE.getIFThenElseSteps_alt1_Elsef();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl10.myDsl.impl.IFThenElseJobsSteps_alt2Impl <em>IF Then Else Jobs Steps alt2</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl10.myDsl.impl.IFThenElseJobsSteps_alt2Impl
     * @see org.xtext.example.mydsl10.myDsl.impl.MyDslPackageImpl#getIFThenElseJobsSteps_alt2()
     * @generated
     */
    EClass IF_THEN_ELSE_JOBS_STEPS_ALT2 = eINSTANCE.getIFThenElseJobsSteps_alt2();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IF_THEN_ELSE_JOBS_STEPS_ALT2__CONDITION = eINSTANCE.getIFThenElseJobsSteps_alt2_Condition();

  }

} //MyDslPackage
