/**
 * generated by Xtext 2.27.0
 */
package org.xtext.example.mydsl10.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Step Options</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl10.myDsl.StepOptions#getStepOption <em>Step Option</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl10.myDsl.MyDslPackage#getStepOptions()
 * @model
 * @generated
 */
public interface StepOptions extends EObject
{
  /**
   * Returns the value of the '<em><b>Step Option</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Step Option</em>' containment reference.
   * @see #setStepOption(EObject)
   * @see org.xtext.example.mydsl10.myDsl.MyDslPackage#getStepOptions_StepOption()
   * @model containment="true"
   * @generated
   */
  EObject getStepOption();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl10.myDsl.StepOptions#getStepOption <em>Step Option</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Step Option</em>' containment reference.
   * @see #getStepOption()
   * @generated
   */
  void setStepOption(EObject value);

} // StepOptions
