/**
 * generated by Xtext 2.27.0
 */
package org.xtext.example.mydsl10.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Steps1</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl10.myDsl.Steps1#getTool_framework_step <em>Tool framework step</em>}</li>
 *   <li>{@link org.xtext.example.mydsl10.myDsl.Steps1#getEnvironemnt_job <em>Environemnt job</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl10.myDsl.MyDslPackage#getSteps1()
 * @model
 * @generated
 */
public interface Steps1 extends EObject
{
  /**
   * Returns the value of the '<em><b>Tool framework step</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl10.myDsl.Tool_framework}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tool framework step</em>' containment reference list.
   * @see org.xtext.example.mydsl10.myDsl.MyDslPackage#getSteps1_Tool_framework_step()
   * @model containment="true"
   * @generated
   */
  EList<Tool_framework> getTool_framework_step();

  /**
   * Returns the value of the '<em><b>Environemnt job</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl10.myDsl.Environment}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Environemnt job</em>' containment reference list.
   * @see org.xtext.example.mydsl10.myDsl.MyDslPackage#getSteps1_Environemnt_job()
   * @model containment="true"
   * @generated
   */
  EList<Environment> getEnvironemnt_job();

} // Steps1
