/*
 * generated by Xtext 2.27.0
 */
package org.xtext.example.mydsl10.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import org.xtext.example.mydsl10.myDsl.Artifact;
import org.xtext.example.mydsl10.myDsl.Command;
import org.xtext.example.mydsl10.myDsl.Environment;
import org.xtext.example.mydsl10.myDsl.IfThenElse;
import org.xtext.example.mydsl10.myDsl.Job;
import org.xtext.example.mydsl10.myDsl.MyDslPackage;
import org.xtext.example.mydsl10.myDsl.Pipeline;
import org.xtext.example.mydsl10.myDsl.Tool_framework;
import org.xtext.example.mydsl10.myDsl.When;
import org.xtext.example.mydsl10.services.MyDslGrammarAccess;

@SuppressWarnings("all")
public class MyDslSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private MyDslGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == MyDslPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case MyDslPackage.ARTIFACT:
				sequence_Artifact(context, (Artifact) semanticObject); 
				return; 
			case MyDslPackage.COMMAND:
				sequence_Command(context, (Command) semanticObject); 
				return; 
			case MyDslPackage.ENVIRONMENT:
				sequence_Environment(context, (Environment) semanticObject); 
				return; 
			case MyDslPackage.IF_THEN_ELSE:
				sequence_IfThenElse(context, (IfThenElse) semanticObject); 
				return; 
			case MyDslPackage.JOB:
				sequence_Job(context, (Job) semanticObject); 
				return; 
			case MyDslPackage.PIPELINE:
				sequence_Pipeline(context, (Pipeline) semanticObject); 
				return; 
			case MyDslPackage.TOOL_FRAMEWORK:
				sequence_Tool_framework(context, (Tool_framework) semanticObject); 
				return; 
			case MyDslPackage.WHEN:
				sequence_When(context, (When) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     Artifact returns Artifact
	 *
	 * Constraint:
	 *     Name3=EString
	 * </pre>
	 */
	protected void sequence_Artifact(ISerializationContext context, Artifact semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MyDslPackage.Literals.ARTIFACT__NAME3) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyDslPackage.Literals.ARTIFACT__NAME3));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getArtifactAccess().getName3EStringParserRuleCall_2_1_0(), semanticObject.getName3());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Command returns Command
	 *
	 * Constraint:
	 *     (
	 *         (tool+=Tool_framework Parameters+=EString) | 
	 *         (
	 *             Description=EString 
	 *             (environment+=Environment environment+=Environment*)? 
	 *             (tool+=Tool_framework Parameters+=EString (tool+=Tool_framework Parameters+=EString)*)?
	 *         )
	 *     )
	 * </pre>
	 */
	protected void sequence_Command(ISerializationContext context, Command semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Environment returns Environment
	 *
	 * Constraint:
	 *     (Key=EString Value=EString)
	 * </pre>
	 */
	protected void sequence_Environment(ISerializationContext context, Environment semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MyDslPackage.Literals.ENVIRONMENT__KEY) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyDslPackage.Literals.ENVIRONMENT__KEY));
			if (transientValues.isValueTransient(semanticObject, MyDslPackage.Literals.ENVIRONMENT__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyDslPackage.Literals.ENVIRONMENT__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getEnvironmentAccess().getKeyEStringParserRuleCall_0_0(), semanticObject.getKey());
		feeder.accept(grammarAccess.getEnvironmentAccess().getValueEStringParserRuleCall_2_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     IfThenElse returns IfThenElse
	 *
	 * Constraint:
	 *     (
	 *         Condition=EString | 
	 *         (Condition=EString (elseif+=IfThenElse elseif+=IfThenElse*)) | 
	 *         (
	 *             Condition=EString 
	 *             if+=Command 
	 *             if+=Command* 
	 *             (((else+=Command else+=Command*)? (elseif+=IfThenElse elseif+=IfThenElse*)) | (elseif+=IfThenElse elseif+=IfThenElse*))?
	 *         ) | 
	 *         (Condition=EString else+=Command else+=Command* (elseif+=IfThenElse elseif+=IfThenElse*)) | 
	 *         (
	 *             (
	 *                 Condition=EString | 
	 *                 (Condition=EString if+=Command if+=Command* (else+=Command else+=Command*)?) | 
	 *                 (Condition=EString else+=Command else+=Command*)
	 *             ) 
	 *             ifelse+=IfThenElse 
	 *             ifelse+=IfThenElse* 
	 *             (elseif+=IfThenElse elseif+=IfThenElse*)
	 *         )
	 *     )?
	 * </pre>
	 */
	protected void sequence_IfThenElse(ISerializationContext context, IfThenElse semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Job returns Job
	 *
	 * Constraint:
	 *     (
	 *         Allow_faillure?='Allow_faillure'? 
	 *         Name1=EString 
	 *         (depends+=[Job|EString] depends+=[Job|EString]*)? 
	 *         (tool_framework_job+=[Tool_framework|EString] tool_framework_job+=[Tool_framework|EString]*)? 
	 *         (output+=[Artifact|EString] output+=[Artifact|EString]*)? 
	 *         (ifthenelse+=[IfThenElse|EString] ifthenelse+=[IfThenElse|EString]*)? 
	 *         (command+=Command command+=Command*)? 
	 *         (input+=Artifact input+=Artifact*)?
	 *     )
	 * </pre>
	 */
	protected void sequence_Job(ISerializationContext context, Job semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Pipeline returns Pipeline
	 *
	 * Constraint:
	 *     (
	 *         Name0=EString? 
	 *         (pipeline_tool_framework+=[Tool_framework|EString] pipeline_tool_framework+=[Tool_framework|EString]*)? 
	 *         (pipeline_envirnonment+=[Environment|EString] pipeline_envirnonment+=[Environment|EString]*)? 
	 *         (when+=When when+=When*)? 
	 *         (job+=Job job+=Job*)?
	 *     )
	 * </pre>
	 */
	protected void sequence_Pipeline(ISerializationContext context, Pipeline semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Tool_framework returns Tool_framework
	 *
	 * Constraint:
	 *     Name5=EString
	 * </pre>
	 */
	protected void sequence_Tool_framework(ISerializationContext context, Tool_framework semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MyDslPackage.Literals.TOOL_FRAMEWORK__NAME5) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyDslPackage.Literals.TOOL_FRAMEWORK__NAME5));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getTool_frameworkAccess().getName5EStringParserRuleCall_1_0(), semanticObject.getName5());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     When returns When
	 *
	 * Constraint:
	 *     Trigger=TRIGGERS
	 * </pre>
	 */
	protected void sequence_When(ISerializationContext context, When semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MyDslPackage.Literals.WHEN__TRIGGER) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyDslPackage.Literals.WHEN__TRIGGER));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getWhenAccess().getTriggerTRIGGERSTerminalRuleCall_0_0(), semanticObject.getTrigger());
		feeder.finish();
	}
	
	
}
