/**
 * generated by Xtext 2.27.0
 */
package org.xtext.example.mydsl10.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Job</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl10.myDsl.Job#isAllow_faillure <em>Allow faillure</em>}</li>
 *   <li>{@link org.xtext.example.mydsl10.myDsl.Job#getName1 <em>Name1</em>}</li>
 *   <li>{@link org.xtext.example.mydsl10.myDsl.Job#getDepends <em>Depends</em>}</li>
 *   <li>{@link org.xtext.example.mydsl10.myDsl.Job#getTool_framework_job <em>Tool framework job</em>}</li>
 *   <li>{@link org.xtext.example.mydsl10.myDsl.Job#getOutput <em>Output</em>}</li>
 *   <li>{@link org.xtext.example.mydsl10.myDsl.Job#getIfthenelse <em>Ifthenelse</em>}</li>
 *   <li>{@link org.xtext.example.mydsl10.myDsl.Job#getCommand <em>Command</em>}</li>
 *   <li>{@link org.xtext.example.mydsl10.myDsl.Job#getInput <em>Input</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl10.myDsl.MyDslPackage#getJob()
 * @model
 * @generated
 */
public interface Job extends EObject
{
  /**
   * Returns the value of the '<em><b>Allow faillure</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Allow faillure</em>' attribute.
   * @see #setAllow_faillure(boolean)
   * @see org.xtext.example.mydsl10.myDsl.MyDslPackage#getJob_Allow_faillure()
   * @model
   * @generated
   */
  boolean isAllow_faillure();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl10.myDsl.Job#isAllow_faillure <em>Allow faillure</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Allow faillure</em>' attribute.
   * @see #isAllow_faillure()
   * @generated
   */
  void setAllow_faillure(boolean value);

  /**
   * Returns the value of the '<em><b>Name1</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name1</em>' attribute.
   * @see #setName1(String)
   * @see org.xtext.example.mydsl10.myDsl.MyDslPackage#getJob_Name1()
   * @model
   * @generated
   */
  String getName1();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl10.myDsl.Job#getName1 <em>Name1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name1</em>' attribute.
   * @see #getName1()
   * @generated
   */
  void setName1(String value);

  /**
   * Returns the value of the '<em><b>Depends</b></em>' reference list.
   * The list contents are of type {@link org.xtext.example.mydsl10.myDsl.Job}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Depends</em>' reference list.
   * @see org.xtext.example.mydsl10.myDsl.MyDslPackage#getJob_Depends()
   * @model
   * @generated
   */
  EList<Job> getDepends();

  /**
   * Returns the value of the '<em><b>Tool framework job</b></em>' reference list.
   * The list contents are of type {@link org.xtext.example.mydsl10.myDsl.Tool_framework}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tool framework job</em>' reference list.
   * @see org.xtext.example.mydsl10.myDsl.MyDslPackage#getJob_Tool_framework_job()
   * @model
   * @generated
   */
  EList<Tool_framework> getTool_framework_job();

  /**
   * Returns the value of the '<em><b>Output</b></em>' reference list.
   * The list contents are of type {@link org.xtext.example.mydsl10.myDsl.Artifact}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Output</em>' reference list.
   * @see org.xtext.example.mydsl10.myDsl.MyDslPackage#getJob_Output()
   * @model
   * @generated
   */
  EList<Artifact> getOutput();

  /**
   * Returns the value of the '<em><b>Ifthenelse</b></em>' reference list.
   * The list contents are of type {@link org.xtext.example.mydsl10.myDsl.IfThenElse}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ifthenelse</em>' reference list.
   * @see org.xtext.example.mydsl10.myDsl.MyDslPackage#getJob_Ifthenelse()
   * @model
   * @generated
   */
  EList<IfThenElse> getIfthenelse();

  /**
   * Returns the value of the '<em><b>Command</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl10.myDsl.Command}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Command</em>' containment reference list.
   * @see org.xtext.example.mydsl10.myDsl.MyDslPackage#getJob_Command()
   * @model containment="true"
   * @generated
   */
  EList<Command> getCommand();

  /**
   * Returns the value of the '<em><b>Input</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl10.myDsl.Artifact}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Input</em>' containment reference list.
   * @see org.xtext.example.mydsl10.myDsl.MyDslPackage#getJob_Input()
   * @model containment="true"
   * @generated
   */
  EList<Artifact> getInput();

} // Job
