/**
 * generated by Xtext 2.27.0
 */
package org.xtext.example.mydsl10.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Pipeline</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl10.myDsl.Pipeline#getName0 <em>Name0</em>}</li>
 *   <li>{@link org.xtext.example.mydsl10.myDsl.Pipeline#getPipeline_tool_framework <em>Pipeline tool framework</em>}</li>
 *   <li>{@link org.xtext.example.mydsl10.myDsl.Pipeline#getPipeline_envirnonment <em>Pipeline envirnonment</em>}</li>
 *   <li>{@link org.xtext.example.mydsl10.myDsl.Pipeline#getWhen <em>When</em>}</li>
 *   <li>{@link org.xtext.example.mydsl10.myDsl.Pipeline#getJob <em>Job</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl10.myDsl.MyDslPackage#getPipeline()
 * @model
 * @generated
 */
public interface Pipeline extends EObject
{
  /**
   * Returns the value of the '<em><b>Name0</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name0</em>' attribute.
   * @see #setName0(String)
   * @see org.xtext.example.mydsl10.myDsl.MyDslPackage#getPipeline_Name0()
   * @model
   * @generated
   */
  String getName0();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl10.myDsl.Pipeline#getName0 <em>Name0</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name0</em>' attribute.
   * @see #getName0()
   * @generated
   */
  void setName0(String value);

  /**
   * Returns the value of the '<em><b>Pipeline tool framework</b></em>' reference list.
   * The list contents are of type {@link org.xtext.example.mydsl10.myDsl.Tool_framework}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pipeline tool framework</em>' reference list.
   * @see org.xtext.example.mydsl10.myDsl.MyDslPackage#getPipeline_Pipeline_tool_framework()
   * @model
   * @generated
   */
  EList<Tool_framework> getPipeline_tool_framework();

  /**
   * Returns the value of the '<em><b>Pipeline envirnonment</b></em>' reference list.
   * The list contents are of type {@link org.xtext.example.mydsl10.myDsl.Environment}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pipeline envirnonment</em>' reference list.
   * @see org.xtext.example.mydsl10.myDsl.MyDslPackage#getPipeline_Pipeline_envirnonment()
   * @model
   * @generated
   */
  EList<Environment> getPipeline_envirnonment();

  /**
   * Returns the value of the '<em><b>When</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl10.myDsl.When}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>When</em>' containment reference list.
   * @see org.xtext.example.mydsl10.myDsl.MyDslPackage#getPipeline_When()
   * @model containment="true"
   * @generated
   */
  EList<When> getWhen();

  /**
   * Returns the value of the '<em><b>Job</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl10.myDsl.Job}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Job</em>' containment reference list.
   * @see org.xtext.example.mydsl10.myDsl.MyDslPackage#getPipeline_Job()
   * @model containment="true"
   * @generated
   */
  EList<Job> getJob();

} // Pipeline
