name: Dotnet



on: [ push ]



jobs:
 build-and-test:
  runs-on: windows-latest 
  
  
  steps:
   - uses: actions/checkout@v4   
   - run: dotnet   restore src\Cfd 
   - run: |
      dotnet test ./Cfd.Tests --logger:"junit;LogFilePath=test-results/dotnet-sample-cfd/xunit.xml"
      mkdir test-results
   - uses: EnricoMi/publish-unit-test-result-action@v2
     if: always()
     with:
      files: |
          './Cfd.Tests/test-results'  
   - uses: actions/upload-artifact@v4
     with:
      name: project
      path: './Cfd.Tests/test-results'