name: Java



on: [ push ]



jobs:
 maven-test:
  runs-on: ubuntu-latest
  
  services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
          
  env:
   POSTGRES_USER : postgres
   POSTGRES_PASSWORD : password
   POSTGRES_DB : cfd
   DOCKERIZE_VERSION : v0.6.1
  
  steps:
   - run: wget   https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz 
   - run: dockerize   -wait tcp://localhost:5432 -timeout 1m 
  