name: Node



on: [ push ]



jobs:
 test:
  runs-on: ubuntu-latest
  
  container:
   image: node:16
   env:
    NODE_ENV: development  
  
  steps:
   - run: checkout 
   - run: yarn install
   - run: yarn  run test:unit 
  
  
  
 cypress-run:
  runs-on: ubuntu-latest
  
  steps:
    - uses: cypress-io/github-action@v6
      with:
       command: yarn  run test:e2e --headless 