name: Pipeline



on: [ push ]


jobs:
 build_and_test:
  runs-on: ubuntu-latest
  container:
   image: node:18
   env:
    NODE_ENV: development
  steps:
   - uses: actions/checkout@v4
   - name: 
     run: yarn i
   - name: Build app
     run: yarn  build 
   - name: Upload artifact
     uses: actions/upload-artifact@v4
     with:
      name: project
      path: ~/project
  
  
  
 deploy:
  runs-on: ubuntu-latest
  container:
   image: node:18
   env:
    NODE_ENV: development  
  
  steps:
   - name: Download artifact
     uses: actions/download-artifact@v4
     with:
       name: project
   - uses: akhileshns/heroku-deploy@v3.12.12 
     with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}} 
          heroku_app_name: "YOUR_HEROKU_APP" 
          heroku_email: "youremai@foo.com" 