name: Python



on: [ push ]



jobs:
 build-and-test:
  runs-on: ubuntu-latest
  container:
   image: cimg/python:3.10.5
   options: --user  root
  
  steps:
   - uses: actions/checkout@v4
   - run: pip install -r requirements.txt 
   - run: pytest 