name: Vue


on: [ push ]



jobs:
 frontend-test:
  if:  vars.runfrontend
  
  runs-on: ubuntu-latest
  
  container:
   image: node:18
   env:
    NODE_ENV: development  
  
  
  steps:
   - run: actions/checkout@v4 
   - run: npm i
   - run: npm  test 
  
  
  
  
 backend-test:
   if:  vars.runbackend
   
   runs-on: ubuntu-latest
   
   container:
    image: cimg/python:3.10.5
    options: --user  root  
   
   steps:
    - run: checkout 
    - run: pip install -r requirements.txt 
    - run: pytest